# Generated by Django 4.2.7 on 2023-11-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialability',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_abilities', to='character.character'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spells',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_list', to='character.spells'),
        ),
        migrations.AlterField(
            model_name='spellstat',
            name='spells',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_stats', to='character.spells'),
        ),
    ]
