# Generated by Django 4.2.7 on 2023-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
