# Generated by Django 4.2.7 on 2023-11-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_abilities_cha_alter_abilities_con_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acitem',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='money',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='weight_caps',
        ),
        migrations.RemoveField(
            model_name='feat',
            name='character',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='savingthrows',
            name='fort',
        ),
        migrations.RemoveField(
            model_name='savingthrows',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='savingthrows',
            name='will',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='character',
        ),
        migrations.RemoveField(
            model_name='specialability',
            name='character',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='spells',
        ),
        migrations.RemoveField(
            model_name='spellstat',
            name='spells',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='combat_info',
        ),
        migrations.RemoveField(
            model_name='character',
            name='player',
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='special_abilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='combat_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='general_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='saving_throws',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Abilities',
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
        migrations.DeleteModel(
            name='AcItem',
        ),
        migrations.DeleteModel(
            name='CombatInfo',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Feat',
        ),
        migrations.DeleteModel(
            name='Gear',
        ),
        migrations.DeleteModel(
            name='GeneralInfo',
        ),
        migrations.DeleteModel(
            name='Money',
        ),
        migrations.DeleteModel(
            name='SavingThrows',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SpecialAbility',
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.DeleteModel(
            name='Spells',
        ),
        migrations.DeleteModel(
            name='SpellStat',
        ),
        migrations.DeleteModel(
            name='Throw',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
        migrations.DeleteModel(
            name='WeightCapacity',
        ),
    ]
