# Generated by Django 4.2.7 on 2023-12-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
    ]
