# Generated by Django 4.2.7 on 2023-11-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_character_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
